name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: oven-sh/setup-bun@v1
      - uses: fish-actions/install-fish@v1
      - run: make setup
      - run: make test-bun
      - run: make test-scripts
      - run: make test-scripts-non-ts
      - run: make lint-ts-biome
      - run: make lint-ts-tsc
      - run: make lint-rust

  bootstrap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: env CODESPACES=true ./bootstrap.sh
